### ISSUE TITLE
Unable to load children for comments tree entity typeorm 

### ISSUE THREAD

**Issue by Jood80** [Survival-DEV/blog-backend#24]
## :memo: What sort of issues is that?
- [ ] Feature
- [x] Bug
- [ ] Enhancement/ Refactor
- [ ] Testing
**Related issues**: 
#10 

### :link:  What endpoint(s) you're working on?
1. `api/comments/`
---------

### Describe your problema:
 - the comments children ain't able to be loaded in the response object 
 > 
 ```json
   {
        "id": "9c522853-9947-46b0-bb51-37898eb9192f",
        "created_at": "2021-07-21T17:28:19.634Z",
        "updated_at": "2021-07-21T17:28:19.634Z",
        "content": "Happy coding in your Eid too",
        "level": 2,
        "children": []
    }, 
  ```

**Any further info needs to be mentioned?**
the current comments tree table looks like this:

```ts
@Entity('comments')
@Tree('closure-table')
export class CommentEntity {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @CreateDateColumn()
  created_at: Date;

  @UpdateDateColumn()
  updated_at: Date;

  @Column({ type: 'varchar' })
  content: string;

  @TreeParent({ onDelete: 'CASCADE' })
  parent: CommentEntity;
  
  @TreeChildren({ cascade: true })
  children: CommentEntity[];
  
  @ManyToOne(() => BlogEntity, blog => blog.comments, { eager: true })
  @JoinColumn({ name: 'blog_id' })
  blog_id: BlogEntity;

  @TreeLevelColumn()
  @Column({ nullable: true })
  level: number;
}
```

**Comment by HumamMajdalawi** [comment]
Hi, you can fix it using entity manager, 
```
const manager = getManager();
const trees = await manager.getTreeRepository(Category).findTrees();
```

I saw your project and its looks very good, I am looking for an open-source project to work on. I will be glad to work with you on this too, 

contact me here if that is possible. 

Best Regards.

**Comment by Jood80** [comment]
@HumamMajdalawi it's nice of you to comment, Thanks!
well, actually it wasn't really a bug. I was able to add the children via `Pgadmin` manually through:
```sql
INSERT INTO comments_closure (id_ancestor, id_descendant)
VALUES (:parent_id, :child_id) ....
```
and I was able to get the whole tree via
```ts
await this.commentTreeRepository.findTrees();
```
here is part of the response
```json
{
        "id": "dfb25b32-ebf4-470a-b15c-9e69fbbf6eec",
        "created_at": "2021-08-07T19:05:24.343Z",
        "updated_at": "2021-08-07T19:05:24.343Z",
        "content": "I'm looking for a cat",
        "parent": null,
        "blog_id": "e7a494be-997e-4e1a-aaa3-f5fdc6b72627",
        "level": 2,
        "replies": [
            {
                "id": "8784fafc-5950-4b67-8ec0-18c44a00a338",
                "created_at": "2021-08-08T12:29:09.296Z",
                "updated_at": "2021-08-08T12:29:09.296Z",
                "content": "why? to clean up your ratty env :smirk:",
                "parent": "dfb25b32-ebf4-470a-b15c-9e69fbbf6eec",
                "blog_id": "e7a494be-997e-4e1a-aaa3-f5fdc6b72627",
                "level": 2,
                "replies": []
            },
````
 However, as I mentioned. This process of connecting the children with their parents was done **manually**. I didn't provide the `create` method in `comment.service` with the part of checking whether the request has a `parent_id` or not, in order to be added as a child/ parent in the first place via typeorm itself not me. This is been updated in this [PR](https://github.com/Survival-DEV/blog-backend/pull/25) #25
